#!/sbin/runscript
# Copyright 1999-2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/net-irc/charybdis/files/charybdis-ircd.initd,v 1.2 2008/01/08 21:17:02 jokey Exp $

depend() {
 	use net
 	provide ircd
}
	
start() {
 	ebegin "Starting ponychat-ircd"
 	start-stop-daemon --start --quiet -u ${PONYCHAT-IRCD_USER} --exec /usr/bin/ircd
 	eend $?
}
 	
stop() {
 	ebegin "Stopping ponychat-ircd"
 	start-stop-daemon --stop --quiet --pidfile ${PONYCHAT-IRCD_PID}
 	eend $?
}

